really drop python <=3.7 support
python-websockets/websockets pull request #1476
Opened 2024-07-02 11:27 UTC by kloczek

Filetrer all cod over `pyupgrade --py38-plus`.

2024-07-02 17:36 UTC, aaugustin requested changes
Some of the changes are valid — e.g. unnecessary imports — but there's also many incorrect changes. Unfortunately it will probably be faster for me to redo the changes than to review and guide you over GitHub comments :-/ I gave up reviewing after a few files because the signal / noise ratio wasn't great.

2024-07-02 17:36 UTC, aaugustin commented on docs/conf.py
> -from websockets.version import tag as version, version as release
That will break generating the docs.

2024-07-02 17:36 UTC, aaugustin commented on example/django/notifications.py
> +
Please avoid gratuitous formatting changes. Also, probably the autoformatter built into the project would revert it at the next commit.

2024-07-02 17:36 UTC, aaugustin commented on example/echo.py
> +
Again, gratuitous change that will make the docs look worse.

2024-07-02 17:38 UTC, aaugustin commented
I think I'm going to redo individual changes — again, faster to redo than review — which will eventually lead to the result that you're aiming for. Thank you for the sugestion! That's a good opportunity to clean up.

2024-07-02 22:33 UTC, kloczek commented
OK so just cannel this PR and do that your way.
If you see some code wrongly filtered please discuss that with `pyupgrade` maintainer.
FYI I've filtered `websockets` code up to --py310-plus and it passes test suite and I don't see any issues on interaction with other modules. code.

2024-07-12 06:14 UTC, aaugustin commented
Union types were introduced in Python 3.10. See https://peps.python.org/pep-0604/. As a consequence, this change isn't compatible with Python 3.8.

```
$ python3.8
Python 3.8.16 (default, Apr  2 2023, 07:49:54)
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo(bar=str | None): pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
>>>
```

```
$ python3.10
Python 3.10.10 (main, Apr  2 2023, 07:49:30) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo(bar=str | None): pass
...
>>>
```

2024-07-12 06:21 UTC, aaugustin commented
Oops. Actually not a problem thanks to `from __future__ import annotations`. I had missed that.

2024-07-12 06:21 UTC, aaugustin commented
Need to check that the docs still generate properly.

2024-07-12 07:44 UTC, aaugustin commented
As of f45286b all the good changes from this PR are in the main branch.

2024-07-12 07:44 UTC, closed without merging